project_name: terraform-provider-restconf
builds:
  - main: ./main.go
    id: "terraform-provider-restconf"
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
archives:
  - format: zip
    name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}'
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
